--NEW CE LOANS Process - is executed for all campaigns where CE_LOANS_EXCL_FIELD in OFFER_T is NOT NULL
--Runs for upto 30 OFFERS to be preset in OFFER_T
--Drafted by Anupam Tripathi 10/1/2018

--FOR SETUP


--Code used to create BPO offers based on selection criteria from CAMPAIGN_EXCLUSIONS_T EXCLUSION_CODE = '1'

START "\\ditech.us\data\GT-Marketing\Production Processes\Campaign Execution\Campaign Waterfalls\BPO Data for Offers (pl sql will require edits for PROC).SQL";
COMMIT;

--State 1 :- These counts are set to zero right now, but are really handy to build models etc.
INSERT INTO AUTO_CE_SOL_CNT
SELECT
ACCOUNT_NUMBER,
SUM(CASE WHEN METHOD_CODE = 'DM' THEN 1 ELSE 0 END) AS DM_CNT,
SUM(CASE WHEN METHOD_CODE = 'EMAIL' THEN 1 ELSE 0 END) AS EMAIL_CNT,
COUNT(*) AS TOT_CNT,
MAX(CASE WHEN METHOD_CODE = 'DM' THEN FILE_OUT_DATE ELSE TO_DATE('01/01/2000','MM/DD/YYYY') END) AS DM_DATE,
MAX(CASE WHEN METHOD_CODE = 'EMAIL' THEN FILE_OUT_DATE ELSE TO_DATE('01/01/2000','MM/DD/YYYY') END) AS EMAIL_DATE
FROM SOLICITATION_HISTORY
WHERE METHOD_CODE IN ('EMAIL', 'DM')
AND CELL_KEY NOT IN (SELECT CELL_KEY FROM CAMPAIGN_CELL_T WHERE SOURCE_CODE IN ('SERVICING', 'NASCAR'))
--AND ROWNUM < 2
GROUP BY ACCOUNT_NUMBER;
COMMIT;

TRUNCATE TABLE AUTO_CE_DATAPULL;
COMMIT;

--Stage 2 Temp table joins to all MDM tables to create a base set of records
INSERT INTO AUTO_CE_DATAPULL
		SELECT
		L.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
		L.SERVICING_SOURCE,
		L.PRIOR_SERVICER_ACCT_NO AS PRIOR_SERVICER_ACCT_NO,
		L.PORTFOLIO AS PORTFOLIO,
		L.LIEN_POSITION AS LIEN_POSITION,
		L.MSR_OWNED_FLAG AS GMAC_OWNED_FLAG,
		--L.ASSOCIATION_CODE AS ASSOCIATION_CODE,
		L.INVESTOR_FULL_NAME AS INVESTOR_FULL_NAME,
		L.INVESTOR_DELIVERY_DATE AS GSE_DELIVERY_DATE,
		L.ORIGINATION_DATE AS ORIGINATION_DATE,
		L.LOAN_AMOUNT AS LOAN_AMOUNT,
		L.UNPAID_BALANCE AS UNPAID_BALANCE,
		L.LOAN_TERM AS LOAN_TERM,
		L.REMAINING_TERM AS REMAINING_TERM,
		L.ADJ_REMAINING_TERM AS ADJ_REMAINING_TERM,
		L.PAYOFF_DATE AS PAYOFF_DATE,
		L.PAYOFF_UPB AS PAYOFF_UPB,
		L.LOAN_STATUS_CODE AS LOAN_STATUS_CODE,
		L.INTEREST_RATE AS INTEREST_RATE,
		L.RATE_TYPE AS RATE_TYPE,
		L.ARM_NEXT_RESET_DATE AS ARM_RESET_DATE,
		L.ARM_NEXT_RESET_RATE AS ARM_RESET_RATE,
		L.PRINCIPAL_AND_INTEREST AS PRINCIPAL_AND_INTEREST,
		L.ESCROW_PAYMENT AS ESCROW_PAYMENT,
		L.PRODUCT_TYPE_CODE AS PRODUCT_TYPE_CODE,
		L.PRODUCT_ID AS PRODUCT_ID,
		L.TEXAS_HE_FLAG AS FLG_TX_HE,
		L.DELQ_12_MTH_STR AS DELQ_12_MTH_STR,
		L.DELINQUENCY_DAYS_PAST_DUE AS DELINQUENCY_DAYS_PAST_DUE,
		L.DELINQUENCY_12_MONTH_COUNT AS DELINQUENCY_12_MONTH_COUNT,
		L.BANKRUPTCY_CODE AS BANKRUPTCY_CODE,
		L.FORECLOSURE_FLAG AS FORECLOSURE_FLAG,
		L.FOREBEARANCE_FLAG AS FLG_FB,
		CASE WHEN L.BPMI_TYPE IN ('A', 'B', 'M', 'O') THEN 'BPMI'
		WHEN L.LPMI_TYPE IN ('A', 'B', 'M', 'O') THEN 'LPMI'
		WHEN L.IPMI_TYPE IN ('A', 'B', 'M', 'O', 'Y') THEN 'IPMI'
		ELSE NULL END AS MI_TYPE,
		CASE WHEN L.BPMI_TYPE IN ('A', 'B', 'M', 'O') THEN L.BPMI_AMT
		WHEN L.LPMI_TYPE IN ('A', 'B', 'M', 'O') THEN L.LPMI_AMT
		ELSE 0 END AS MI_AMOUNT,
		CASE WHEN L.BPMI_TYPE IN ('A', 'B', 'M', 'O') THEN L.BPMI_ENDORSEMENT_DATE
		WHEN L.LPMI_TYPE IN ('A', 'B', 'M', 'O') THEN L.LPMI_ENDORSEMENT_DATE
		ELSE NULL END MI_ENDORSEMENT_DATE,
		L.BPMI_AMT,                                       -- JE Added 6/17/15 for Temp suppression of BPMI
		L.LAST_NAME_PRIM AS LAST_NAME_PRIM,
		L.FIRST_NAME_PRIM AS FIRST_NAME_PRIM,
		L.FULL_NAME_PRIM AS FULL_NAME_PRIM,
		L.SSN_PRIM AS SSN_PRIMARY,
		L.MAIL_ADDRESS1_PRIM AS ADDRESS1,
		L.MAIL_ADDRESS2_PRIM AS ADDRESS2,
		L.MAIL_CITY_PRIM AS CITY,
		L.MAIL_STATE_PRIM AS STATE,
		L.MAIL_ZIP_PRIM AS ZIP,
		L.HOME_PHONE_PRIM AS HOME_PHONE,
		L.EMAIL_ADDRESS_PRIM AS EMAIL_ADDRESS,
        L.EMAIL_ADDRESS_SECD, --Added by AT on 2/12/2016 to include secondary email addresses
        L.DNS_EMAIL_FLAG_SECD, --Added by AT on 2/12/2016 to include secondary email addresses
		L.DNS_MAIL_FLAG AS DNS_MAIL_FLAG,
		L.DNS_PHONE_FLAG AS DNS_PHONE_FLAG,
		L.DNS_EMAIL_FLAG_PRIM AS DNS_EMAIL_FLAG,
		L.STD_EXCLUSION_FM_FLAG AS STD_EXCLUSION_FM_FLAG,
		L.ACTIVE_DUTY_FLAG,
		L.DO_NOT_SHARE_3RD_PARTY AS DO_NOT_SHARE_3RD_PARTY_FLG,
		L.DO_NOT_SHARE_MARKETING AS DO_NOT_SHARE_MKTG_FLG,
		L.DO_NOT_MARKET_FLAG AS DO_NOT_MARKET_FLAG,
		L.EMPLOYEE_FLAG AS GT_EMPLOYEE_FLG,
		L.ORIGINAL_FICO_PRIM AS ORIGINAL_FICO,
		L.CURRENT_FICO_PRIM AS CURRENT_FICO,
		L.LAST_NAME_SECD AS LAST_NAME_SECD,
		L.FIRST_NAME_SECD AS FIRST_NAME_SECD,
		L.FULL_NAME_SECD AS FULL_NAME_SECD,
		L.SSN_SECD AS SSN_SECONDARY,
		L.PROP_ADDRESS1 AS PROP_ADDRESS1,
		L.PROP_ADDRESS2 AS PROP_ADDRESS2,
		L.PROP_CITY AS PROP_CITY,
		L.PROP_STATE AS PROP_STATE,
		L.PROP_ZIP AS PROP_ZIP,
		L.ORIGINAL_LTV AS ORIGINAL_LTV,
		L.CURRENT_PROPERTY_VALUE AS CURRENT_PROPERTY_VALUE,
		L.CURRENT_PROP_VALUE_METHOD AS CURRENT_PROPERTY_METHOD,
		L.CURRENT_PROP_VALUE_DATE AS CURRENT_PROPERTY_DATE,
		L.LTV AS LTV,
		L.CURRENT_OCCUPANCY_CODE AS CURRENT_OCCUPANCY_CODE,
		L.PROPERTY_TYPE AS VENDOR_PROP_TYPE,
		L.PROPERTY_TYPE_CODE AS PROPERTY_TYPE_CODE,
		L.NUMBER_OF_UNITS AS NUMBER_OF_UNITS,
		L.RETAINED_FLAG AS RETAINED_FLAG,
		L.RETAINED_ACCT_NO AS RETAINED_ACCT_NO,
		L.PORTFOLIO_SUBGROUP AS PORTFOLIO_SUBGROUP,
		L.UNIQUE_ID AS UNIQUE_ID,
		L.DATE_BOARDED,
		A.FLG_APP_PIPELINE,
		A.FLG_APP_LEAD,
		A.FLG_APP_DENIED,
		A.FLG_APP_WITHDRAWN,
		CASE WHEN L.CURRENT_PROP_VALUE_METHOD IN ('IPV', 'HVE') THEN 'N' ELSE 'Y' END AS FLG_GSE_VALUE,
		--Modified by AT on 05/11/2015 to include Freddie loans where method is HVE
		CASE WHEN F.ALTA_FLG IS NULL THEN 'N' ELSE ALTA_FLG END AS FLG_ALTA,
		CASE WHEN F.EA_FLG IS NULL THEN 'N' ELSE EA_FLG END AS FLG_EA,
		CASE WHEN F.SUBPRIME_FLG IS NULL THEN 'N' ELSE SUBPRIME_FLG END AS FLG_SUBPRIME,
		CASE WHEN CE_FLG IS NULL THEN 'N' ELSE CE_FLG END AS FLG_CE,
		'N' AS FLG_RECOURSE,
		'N' AS FLG_REPURCHASE,
		CASE WHEN LENGTH(REPLACE(L.DELQ_12_MTH_STR,'0','')) > 1 THEN 'Y' ELSE 'N' END FLG_DQ12,
		CASE WHEN LENGTH(REPLACE(SUBSTR(L.DELQ_12_MTH_STR,7,6),'0','')) > 0 THEN 'Y' ELSE 'N' END FLG_DQ6,
		CASE WHEN L.DELINQUENCY_DAYS_PAST_DUE > 30 THEN 'Y' ELSE 'N' END FLG_DQCUR,
		--  Added 5/6/15 JE (for TUSTIN OBTM)
		CASE WHEN MA.PRIOR_ACCOUNT_NO IS NOT NULL AND MA.APP_STATUS_GRP IN ('Pipeline','Funded','Cancelled') THEN 'Y' ELSE 'N' END FLG_PRIOR_APP,
		L.LATE_FEE,           -------  LFR.LATEOS,   -- Added 7/2/15 JE (for LATE FEE CELLS) - Now pull from MDM_LOAN
		L.MARKETING_ELIGIBILITY,   -- Added 7/6/15 JE (for LATE FEE CELLS)
		--  Added 7/31/15 JE (Set temporary flag for Everbank records)
		CASE WHEN L.ASSET_OWNER_PORTFOLIO IN ('EBGM050214' , 'EVER050114', 'GTEB060215' ) THEN 'Y' ELSE 'N' END  EVERBANK_FLAG,
        CASE WHEN L.DECEASED_FLAG IN ('B','C','P') THEN L.DECEASED_FLAG ELSE
		CASE WHEN ((UPPER(L.FIRST_NAME_PRIM) LIKE '%DECEASED%' or UPPER(L.LAST_NAME_PRIM) LIKE '%DECEASED%') AND (UPPER(L.FIRST_NAME_SECD) LIKE '%DECEASED%' or UPPER(L.LAST_NAME_SECD) LIKE '%DECEASED%')) THEN 'B'
		WHEN (UPPER(L.FIRST_NAME_PRIM) LIKE '%DECEASED%' or UPPER(L.LAST_NAME_PRIM) LIKE '%DECEASED%') THEN 'P'
		WHEN (UPPER(L.FIRST_NAME_SECD) LIKE '%DECEASED%' or UPPER(L.LAST_NAME_SECD) LIKE '%DECEASED%') THEN 'C'
		ELSE 'N' END END AS DECEASED_FLAG,     --  Added 8/11/15 JE --MODIFIED BY AT ON 4/19/2017 TO ALLOW SECD MKTG IF PRIMARY IS DECEASED
		L.MOD_STATUS, -- Added by AT to reactivate MOD Flag
		CASE WHEN FMOD.FNMA_LN IS NULL THEN 'Y' ELSE 'N' END FLG_NOT_FNMA_MOD,   --  Added 8/26/15 JE (for HAMP to HARP Cell)
		--------CASE WHEN MSP_MOD.MSP_LOAN_NBR IS NULL THEN 'Y' ELSE 'N' END FLG_NOT_MSP_MOD,   --  Added 10/5/15 JE (for Non Fannie [Freddie] MOD cell)
		CASE WHEN HAMP_MOD.ACCOUNT_NUMBER IS NULL THEN 'Y' ELSE 'N' END FLG_NOT_HAMP_MOD,   --  Added 2/17/16 JE (for Non Fannie [Freddie] MOD cell)

		'N' as FLG_SWEEPS_ENROLLED,  --- Added 1/12/18 - Does use field anymore but keep so offer still works for field
		------CASE WHEN SR.ACCOUNT_NUMBER IS NOT NULL THEN 'Y' ELSE 'N' END FLG_SWEEPS_ENROLLED,   -- Added 9/23/15 JE (for Sweeps Enrollment)

		CASE WHEN USAA.ACCOUNT_NUMBER IS NOT NULL AND NVL(L.LTV,0) < 80 THEN 'Y' ELSE 'N' END FLG_USAA_ACCOUNT,    -- Modified by AT to include LTV Added 9/30/15 JE (for MDM USAA Accounts)
		MA.APP_RATE_LOCK_DATE,         -- Added 11/20/15 JE (for Cyber Monday Email /  $250 VGC December self-mailer)
		ANW.HARP_ELIGIBLE,            -- Added 3/24/16 JE (for APRIL Matrix)
		CASE WHEN BK.ACCOUNT_NUMBER IS NULL THEN 1000
		WHEN NVL(BK.SOLICITABLE,'Y') = 'N' OR NVL(BK.REFI_ELIGIBILITY,'AFTER WAIT') <> 'AFTER WAIT' THEN -1
		ELSE BK_MTHS_SINCE END AS BK_MTHS_SINCE --Added by AT on 4/17/2016 to Supp Closed B/K


        ----,NVL(ANW.MODEL_SCORE_PCT,0) AS MODEL_SCORE_PCT --Added by AT on 5/4/16 to get model score from ANW
        ----,NVL(MODEL_DECILE,11) AS MODEL_DECILE --Added by AT on 5/4/16 to get model score from ANW

        ,' ' AS MODEL_SCORE_PCT --Added by JE on 02/06/2018 to get model score from ANW
        ,' ' AS MODEL_DECILE --Added by JE on 02/06/2018 to get model score from ANW

        ,L.LOAN_TYPE                          --Added by JE on 6/13/16 for FHA to FHA offer criteria
        ,NVL(REST.REST_PERIOD,'XXXX') AS REST_PERIOD		-- Added by AT on 8/24/2016 to implement Resting Strategy
		,L.LOANSRV_CD
		,L.CELLPHONE_CALLS_INDICATOR
		,L.CELLPHONE_NUMBER
		,DM_CAT1.DM_CAT1
		,DM_CAT2.DM_CAT2
        ,MBC.CLUSTER_GRP
        ,ROUND(DM_CAT1.PCT_PROD_SCORE,3) AS PCT_PROD_SCORE1
        ,ROUND(DM_CAT1.PCT_RESPONSE_SCORE,3) AS PCT_RESPONSE_SCORE1
        ,ROUND(DM_CAT1.MARGIN,3) AS MARGIN1
		,ROUND(DM_CAT2.PCT_PROD_SCORE,3) AS PCT_PROD_SCORE2
        ,ROUND(DM_CAT2.PCT_RESPONSE_SCORE,3) AS PCT_RESPONSE_SCORE2
        ,ROUND(DM_CAT2.MARGIN,3) AS MARGIN2
        ,DM_CAT0.DM_CAT0

        ,CASE WHEN
				(
				(NVL(L.DNS_EMAIL_FLAG_PRIM,'N') = 'N' and L.EMAIL_ADDRESS_PRIM IS NOT NULL AND L.EMAIL_ADDRESS_PRIM LIKE ('%@%')AND L.EMAIL_ADDRESS_PRIM LIKE ('%.%')) --Primay
				or
				(NVL(L.DNS_EMAIL_FLAG_SECD,'N') = 'N' and L.EMAIL_ADDRESS_SECD IS NOT NULL and L.EMAIL_ADDRESS_SECD LIKE ('%@%')and L.EMAIL_ADDRESS_SECD LIKE ('%.%')) --Secd
				 ) THEN 'N' ELSE 'Y' END AS EMAIL_FLG
		,CASE WHEN (DNS_PHONE_FLAG = 'Y' OR LENGTH(L.HOME_PHONE_PRIM) <> 10  OR LENGTH(L.HOME_PHONE_PRIM) IS NULL OR trim(L.HOME_PHONE_PRIM)='0000000000') THEN 'Y' ELSE 'N' END AS PHONE_FLG
        ,SOL_CNT.DM_CNT -- AT 7/13/2016
		,SOL_CNT.EMAIL_CNT -- AT 7/13/2016
		,SOL_CNT.DM_DATE -- AT 7/13/2016
		,SOL_CNT.EMAIL_DATE -- AT 7/13/2016
		,SOL_CNT.TOT_CNT

		FROM MDM_LOAN L,

		AT_NEW_WATERFALL ANW,              -- Added 3/24/16 JE (for APRIL Matrix)
		VW_APP_SUPPRESSIONS_GREENTREE A,
		STREAMLINE_HARP_FNMA_SOL F,
		---------LATE_FEE_RECORDS LFR,         -- Added 7/2/15 JE (for LATE FEE CELLS) - NOW Pull from MDM_LOAN
		AT_FNMA_MOD FMOD,                      -- Added 8/26/15 JE (for HAMP to HARP Cell)

		-----(SELECT DISTINCT(ACCOUNT_NUMBER) FROM SWEEPSTAKES_RESPONDER) SR,   -- Added 9/23/15 JE (SWEEPSTAKES RESPONDERS)
		MDM_USAA_ACCOUNTS USAA,                      -- Added 9/30/15 JE (for MDM USAA Accounts)
		-----------AT_MSP_MOD MSP_MOD,                          -- Added 10/5/15 JE (for Non Fannie [Freddie] MOD cell)

		(                     -- Added 2/17/16 JE (for Non Fannie [Freddie] MOD cell)
		   --CHANGED BY AT ON 7/716 TO FETCH DATA FROM NEW HAMP MOD TABLE
		   SELECT DISTINCT ACCOUNT_NUMBER FROM MDM_HAMP_MOD_2016_06
		   /*
		   select SERVICERLOANNUMBER,SERVICING_SOURCE, ACCOUNT_NUMBER
           from MDM_HAMP_MOD
           where LOANMODIFICATIONMODENAME in ('Trial Period Modification','Official Modification') and  LOANSTATENAME in ('Active','Active Payment' )
           and ACCOUNT_NUMBER is not null
           and MOD_RANK=1*/
        ) HAMP_MOD,

		(
		SELECT * FROM
			( SELECT X.*,
				RANK() OVER (PARTITION BY X.PRIOR_ACCOUNT_NO order by APP_NO DESC) AS RANK
				FROM MDM_APP X
				WHERE PRIOR_ACCOUNT_NO IS NOT NULL
			)
		WHERE RANK = 1
		) MA, -- Added 5/6/15 JE (for TUSTIN OBTM)
        VW_CLOSED_BK_SUPP BK, --Added by AT on 4/7/2016 to suppress Closed B/K based on waiting period
        (
			SELECT * FROM
				(
					SELECT
					A.*,
					RANK() OVER(PARTITION BY ACCOUNT_NUMBER ORDER BY DATE_ADDED DESC, ROWNUM) AS RANK
					FROM
					CE_RESTING_LIST A
				)
			WHERE RANK = 1
        ) REST,   -- Modified by AT on 01/06/2017 to implement Resting Strategy by date

        (SELECT ACCOUNT_NUMBER, DM_CAT AS DM_CAT1, PCT_PROD_SCORE, PCT_RESPONSE_SCORE, ROUND(MARGIN,2) AS MARGIN FROM MDL_WEEKLY_DM_SCORES WHERE DM_CAT <> 0 AND DM_CAT <= 7) DM_CAT1,
        (SELECT ACCOUNT_NUMBER, DM_CAT AS DM_CAT2, PCT_PROD_SCORE, PCT_RESPONSE_SCORE, ROUND(MARGIN,2) AS MARGIN FROM MDL_WEEKLY_DM_SCORES WHERE DM_CAT <> 0 AND DM_CAT > 7) DM_CAT2,

        --- For August 2018 Filler group
        (SELECT ACCOUNT_NUMBER, DM_CAT AS DM_CAT0, PCT_PROD_SCORE, PCT_RESPONSE_SCORE, ROUND(MARGIN,2) AS MARGIN FROM MDL_WEEKLY_DM_SCORES WHERE DM_CAT = 0 AND period='Second Half') DM_CAT0,



        	(
			SELECT * FROM
				(
				SELECT RANK() OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY ROWNUM) AS RANK,M.*
				FROM  MDL_BORROWER_CLUSTERS M
				)
			WHERE RANK = 1
			) MBC,

			AUTO_CE_SOL_CNT SOL_CNT

		WHERE L.ACCOUNT_NUMBER = A.ACCOUNT_NUMBER(+)

        AND L.ACCOUNT_NUMBER = MBC.ACCOUNT_NUMBER(+)       -- Added 9/19/17 JE (for EMAIL Cluster info)
		AND L.ACCOUNT_NUMBER = ANW.ACCOUNT_NUMBER(+)       -- Added 3/24/16 JE (for APRIL Matrix)

		AND L.ACCOUNT_NUMBER = MA.PRIOR_ACCOUNT_NO(+)      -- Added 5/6/15 JE (for TUSTIN OBTM)
		----------AND L.ACCOUNT_NUMBER = LFR.ACCOUNT_NUMBER(+)  -- Added 7/2/15 JE (for LATE FEE CELLS)  NOW Pull MDM_LOAN
		AND L.INVESTOR_LOAN_NO = FMOD.FNMA_LN(+)           -- Added 8/26/15 JE (for HAMP to HARP Cell)
		-------AND L.ACCOUNT_NUMBER = SR.ACCOUNT_NUMBER(+)        -- Added 9/23/15 JE (for SWEEPSTAKES RESPONDERS)
		AND L.ACCOUNT_NUMBER = USAA.ACCOUNT_NUMBER(+)      -- Added 9/30/15 JE (for MDM USAA Accounts)
		--------AND TRIM(LEADING '0' FROM L.ACCOUNT_NUMBER) = MSP_MOD.MSP_LOAN_NBR(+)  -- Added 10/5/15 JE (for Non Fannie [Freddie] MOD cell)
		AND L.ACCOUNT_NUMBER = HAMP_MOD.ACCOUNT_NUMBER(+)     -- Added 2/17/16 JE (for Non Fannie [Freddie] MOD cell)
		AND L.INVESTOR_LOAN_NO = F.FNMA_LN(+)
		AND L.ACCOUNT_NUMBER = BK.ACCOUNT_NUMBER(+)
		AND L.ACCOUNT_NUMBER = REST.ACCOUNT_NUMBER(+) -- Added by AT on 8/24/2016 to implement Resting Strategy
		AND L.ACCOUNT_NUMBER = DM_CAT1.ACCOUNT_NUMBER(+)
		AND L.ACCOUNT_NUMBER = DM_CAT2.ACCOUNT_NUMBER(+)
		AND L.ACCOUNT_NUMBER = DM_CAT0.ACCOUNT_NUMBER(+)
		AND L.ACCOUNT_NUMBER = SOL_CNT.ACCOUNT_NUMBER(+)
		--------AND L.MARKETING_ELIGIBILITY = 'Y'     --- removed 2/5/19
		AND L.LOAN_STATUS_CODE = '1'
		AND L.LIEN_POSITION IN ('01','02')
		AND L.PAYOFF_DATE IS NULL
		AND L.UNPAID_BALANCE > 0;
COMMIT;

--Recreate CE Loans with Hubspot valid EMAIL ADDRESSES
TRUNCATE TABLE CE_LOANS;
COMMIT;

INSERT INTO CE_LOANS
SELECT
A.ACCOUNT_NUMBER,
A.SERVICING_SOURCE,
A.UNIQUE_ID,
E.EMAIL_ADDRESS AS HUBSPOT_EMAIL_ADDRESS,
--NULL AS OFFER_1,
NULL AS EXCL_1,
--NULL AS OFFER_2,
NULL AS EXCL_2,
--NULL AS OFFER_3,
NULL AS EXCL_3,
--NULL AS OFFER_4,
NULL AS EXCL_4,
--NULL AS OFFER_5,
NULL AS EXCL_5,
--NULL AS OFFER_6,
NULL AS EXCL_6,
--NULL AS OFFER_7,
NULL AS EXCL_7,
--NULL AS OFFER_8,
NULL AS EXCL_8,
--NULL AS OFFER_9,
NULL AS EXCL_9,
--NULL AS OFFER_10,
NULL AS EXCL_10,
--NULL AS OFFER_11,
NULL AS EXCL_11,
--NULL AS OFFER_12,
NULL AS EXCL_12,
--NULL AS OFFER_13,
NULL AS EXCL_13,
--NULL AS OFFER_14,
NULL AS EXCL_14,
--NULL AS OFFER_15,
NULL AS EXCL_15,
--NULL AS OFFER_16,
NULL AS EXCL_16,
--NULL AS OFFER_17,
NULL AS EXCL_17,
--NULL AS OFFER_18,
NULL AS EXCL_18,
--NULL AS OFFER_19,
NULL AS EXCL_19,
--NULL AS OFFER_20,
NULL AS EXCL_20,
--NULL AS OFFER_21,
NULL AS EXCL_21,
--NULL AS OFFER_22,
NULL AS EXCL_22,
--NULL AS OFFER_23,
NULL AS EXCL_23,
--NULL AS OFFER_24,
NULL AS EXCL_24,
--NULL AS OFFER_25,
NULL AS EXCL_25,
--NULL AS OFFER_26,
NULL AS EXCL_26,
--NULL AS OFFER_27,
NULL AS EXCL_27,
--NULL AS OFFER_28,
NULL AS EXCL_28,
--NULL AS OFFER_29,
NULL AS EXCL_29,
--NULL AS OFFER_30,
NULL AS EXCL_30
FROM AUTO_CE_DATAPULL A,
VW_HUBSPOT_EMAILS E
WHERE A.ACCOUNT_NUMBER = E.ACCOUNT_NUMBER(+);
COMMIT;

TRUNCATE TABLE AUTO_CE_SOL_CNT;
COMMIT;

exec dbms_stats.gather_table_stats(ownname=>'CSRG_PROD',tabname=>'CE_LOANS');
exec dbms_stats.gather_table_stats(ownname=>'CSRG_PROD',tabname=>'AUTO_CE_DATAPULL');
exec dbms_stats.gather_table_stats(ownname=>'CSRG_PROD',tabname=>'AUTO_CE_BPO');
commit;

ANALYZE TABLE AUTO_CE_DATAPULL COMPUTE STATISTICS;
ANALYZE TABLE CE_LOANS COMPUTE STATISTICS;
ANALYZE TABLE AUTO_CE_BPO COMPUTE STATISTICS;
COMMIT;


--Create SQL for all exclusions including BPO criteria e.g. exclusion code 3021 for PI savings and apply exclusions
START "\\ditech.us\data\GT-Marketing\Production Processes\Campaign Execution\Campaign Waterfalls\Exclusion from CET (pl sql will require edits for PROC)";
COMMIT;

--TBD - do we want this table or not?
/*
TRUNCATE TABLE AUTO_CE_DATAPULL;
COMMIT; */
