DROP VIEW VW_HUBSPOT_EMAILS;
CREATE VIEW VW_HUBSPOT_EMAILS AS
SELECT ACCOUNT_NUMBER, EMAIL_ADDRESS FROM
(
	SELECT
	Z.*,
	RANK() OVER(PARTITION BY ACCOUNT_NUMBER ORDER BY BORROWER_TYPE, CURRENT_OCCUPANCY_CODE, ORIGINATION_DATE DESC, UNPAID_BALANCE DESC,ROWNUM) AS AN_RANK
	FROM

	(
			SELECT
			A.*,
			RANK() OVER(PARTITION BY EMAIL_ADDRESS ORDER BY BORROWER_TYPE, CURRENT_OCCUPANCY_CODE, ORIGINATION_DATE DESC, UNPAID_BALANCE DESC,ROWNUM) AS EMAIL_RANK
			FROM
			(
					SELECT
					ACCOUNT_NUMBER,
					1 AS BORROWER_TYPE,
					UPPER(EMAIL_ADDRESS_PRIM) AS EMAIL_ADDRESS,
					ORIGINATION_DATE,
					CURRENT_OCCUPANCY_CODE,
					UNPAID_BALANCE
					FROM MDM_LOAN
					WHERE LOAN_STATUS_CODE = '1'
					AND EMAIL_ADDRESS_PRIM IS NOT NULL
					AND EMAIL_ADDRESS_PRIM LIKE ('%@%')
			        AND NVL(DNS_EMAIL_FLAG_PRIM,'N') = 'N'

					UNION ALL

					SELECT
					ACCOUNT_NUMBER,
					2 AS BORROWER_TYPE,
					UPPER(EMAIL_ADDRESS_SECD) AS EMAIL_ADDRESS,
					ORIGINATION_DATE,
					CURRENT_OCCUPANCY_CODE,
					UNPAID_BALANCE
					FROM MDM_LOAN
					WHERE LOAN_STATUS_CODE = '1'
					AND EMAIL_ADDRESS_SECD IS NOT NULL
					AND EMAIL_ADDRESS_SECD LIKE ('%@%')
					AND NVL(DNS_EMAIL_FLAG_SECD,'N') = 'N'
			) A


	) Z

	WHERE EMAIL_RANK = 1
)
WHERE AN_RANK = 1

;
COMMIT;

SELECT COUNT(*) FROM VW_HUBSPOT_EMAILS;        --- Before = 852927    After = 840870

-- QC checks
select count(*),count(distinct lower(email_address)) from VW_HUBSPOT_EMAILS;
--840870	840870
select count(*),count(distinct account_number) from VW_HUBSPOT_EMAILS;
--840870	840870


select lower(email_address) as email,count(*) from VW_HUBSPOT_EMAILS group by lower(email_address) having count(*)>1;
