PROC SQL;      
		CONNECT TO ORACLE AS CONN1 (USER=CSRG_PROD ORAPW='MRDM$101' PATH="RENPU") ;
			
			CREATE table ECR_DATAPULL  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(SELECT
          				 L1.ACCOUNT_NUMBER
          			    ,L1.ASSOCIATION_GROUP as LOAN_AG
						,L1.ASSOCIATION_CODE
					   , L1.PRIMARY_CUSTOMER_ID
					   , L1.SECONDARY_CUSTOMER_ID
          		       , L1.PRODUCER_EMP_ID
          		       , C1.ORIGINAL_LOAN_NUMBER
          		       , C1.MASTER_HOLDOUT_GROUP_FLAG
          		       , C1.ANY_BANKRUPTCY_FLAG
          		       , C1.ANY_DNS_EMAIL_FLAG
          		       , C1.ANY_DNS_MAIL_FLAG
          		       , C1.ANY_DNS_PHONE_FLAG
          		       , C1.ANY_FORECLOSURE_FLAG
          		       , C1.ANY_GLBA_INDICATOR
          		       , C1.EMAIL_ADDRESS
          		       , L1.HE_ACCOUNT_ACCESS_NUMBER as ACCOUNT_ACCESS_NUMBER
          		     , L1.REMAINING_TERM
                     , L1.PURPOSE_CODE
                     , L1.PAYMENT_PROGRAM_CODE
					 ,L1.ARM_RESET_DATE AS PAYMENT_RATE_ADJ_DATE
          		      , L1.PREPAYMENT_PENALTY_CODE as PPP_CODE
                     , C1.ANY_FIRST_MORTGAGE_FLAG
                     , C1.ANY_HE_FLAG
                     , C1.CURRENT_FICO_SCORE
					 ,C1.RELATIONSHIP_START_DATE
                     , C1.PRIZM_CODE
                     , C1.GMF_FLAG as GMF_LOGO
                     , C1.GMF_STANDARD_DESCRIPTION
                     , DECODE(C1.GMF_LOGO,'GMFF','Y','N') as GM_LOGO_FLAG
                     , C1.CUSTOMER_MASTER_FLAG
                     , C1.MARKETING_CONTACT_EMP_ID as MKT_CONTACT_EMP_ID
                     , C1.MARKETING_CONTACT_NAME   as MKT_CONTACT_NAME
                     , C1.MARKETING_CONTACT_PHONE  as MKT_CONTACT_PHONE
                     , C1.MARKETING_CONTACT_WHICH  as MKT_CONTACT_WHICH
                     , C1.MARKETING_BRANCH_ID      as MKT_CONTACT_BRANCH_ID
                     , C1.MARKETING_LOAN_NUMBER      as  MARKETING_LOAN_NUMBER
                     , C1.SSN as PRIMARY_SSN
                     , C1.FIRST_NAME   as PRIM_NAME_FIRST
                     , C1.MIDDLE_NAME  as PRIM_NAME_MIDDLE
                     , C1.LAST_NAME    as PRIM_NAME_LAST
                     , C1.HOME_PHONE   as PHONE_HOME_PRIMARY_BORROWER
                     , C1.WORK_PHONE   as PHONE_WORK_PRIMARY_BORROWER
                     , C1.CURRENT_ADDRESS_ID
                     , C1.PERSISTENT_INDIVIDUAL_ID as PRIMARY_COMMON_ID
                     , C1.GMACNAO_RELATIONSHIP_CODE
                     , C1.GMACI_RELATIONSHIP_CODE
					 , C1.ANY_GLBA_INDICATOR
                     , A2.ADDRESS_LINE_1 as ADDRESS_1
                     , A2.ADDRESS_LINE_2 as ADDRESS_2
                     , A2.CITY           as CITY
                     , A2.STATE          as STATE
                     , A2.ZIP            as ZIP
                     , A2.ZIP4			 as ZIP4
                     , A2.GIS_STATE_COUNTY as GIS_STATE_COUNTY
                     , DECODE(C2.SSN,'000000000',NULL,C2.SSN) as SECONDARY_SSN
                     , C2.FIRST_NAME   as SCND_NAME_FIRST
                     , C2.MIDDLE_NAME  as SCND_NAME_MIDDLE
                     , C2.LAST_NAME    as SCND_NAME_LAST
                     , C2.PERSISTENT_INDIVIDUAL_ID as SECONDARY_COMMON_ID
                     , L1.ORIGINATION_BRANCH_ID
                     , L1.GMAC_OWNED_FLAG as GM_OWNED
                     , L1.PREPAYMENT_PENALTY_EXPIRATION as PPP_DATE
                     , L1.EXPUR_FLAG
                     , L1.EXREF_FLAG
                     , L1.UNPAID_BALANCE as BAL_PRIN
                     , L1.PRIMARY_TYPE_CODE as  LOAN_MORT_TYPE
                     , L1.PROPERTY_ID
					 , L1.BANKRUPTCY_CODE
                     , L1.ARM_FLAG as ARM_IND
                     , L1.DELINQUENCY_18_MONTH_COUNT
                     , L1.DELINQUENCY_12_MONTH_COUNT as DELQ_COUNT_TOTAL
                     , L1.DELINQUENCY_DAYS_PAST_DUE as DELQ_DAYS_FROM_DUE
                     , L1.FROZEN_CODE
                     , L1.STD_EXCLUSION_FM_FLAG
                     , L1.STD_EXCLUSION_HE_FLAG
                     , L1.STD_EXCLUSION_MAS_FLAG
					 , L1.STD_EXCLUSION_AP_FLAG
					 , L1.DNS_MAIL_FLAG
					 , L1.DNS_PHONE_FLAG
					 , L1.SERVICING_CODE
					 , L1.UNIQUE_ID
					 , L1.PAYMENT_CALC_FREQUENCY
					 , L1.PAYMENT_METHOD_CODE
					 , L1.PRIMARY_TYPE_CODE
                     , L1.PRODUCT_ID
                     , L1.BALLOON_TYPE_CODE
                     , L1.LIEN_POSITION as LIEN_LEVEL_CODE
                     , L1.LOAN_TERM
                     , L1.INTEREST_RATE
                     , L1.LOAN_AMOUNT
                     , L1.TOTAL_PAYMENT
                     , L1.PRINCIPAL_AND_INTEREST
                     , L1.LAST_PAYMENT_DATE
                     , L1.NEXT_PAYMENT_DUE_DATE
                     , L1.ORIGINATION_DATE        as LOAN_ORIG_DT
					 ,CASE WHEN L1.ORIGINATION_DATE > SYSDATE - 180 THEN 'Y' ELSE 'N' END AS FLG_AGE
                     , L1.SERVICING_ACTIVE_DATE   as LOAN_SERV_ACTV_DT
                     , L1.HE_CREDIT_LIMIT         as LINE_COMMIT_AMT
                     , L1.PRIMARY_TYPE_CODE as TYPE_CODE
                     , L1.SECONDARY_TYPE_CODE as TYPE_SUB_CODE
                     , L1.LOAN_ADDRESS_ID
                     , L1.PAYOFF_REFI_SCORE
                     , L1.PAYOFF_MOVER_SCORE
                     , L1.LOAN_ID          as LOAN_LOAN_ID
                     , L1.SUBPRIME_FLAG
                     , L1.HFN_REFI_ELIGIBLE_FLAG
                     , L1.RATE_TYPE
					 , L1.GMF_FULL_DESCRIPTION
                     , L1.HOLD_FOR_INVESTMENT_IND
                     , L1.INVESTOR_NUMBER
					 , L1.INVESTOR_FULL_NAME
				    , A3.ADDRESS_LINE_1   as LOAN_ADDRESS1
                     , A3.ADDRESS_LINE_2   as LOAN_ADDRESS2
                     , A3.CITY             as LOAN_CITY
                     , A3.STATE            as LOAN_STATE
                     , A3.ZIP              as LOAN_ZIP
                     , P1.MOST_RECENT_SALE_AMOUNT as SALE_AMT
                     , P1.PROPERTY_TYPE_CODE	    as PROPERTY_TYPE_CODE
                     , P1.CURRENT_OCCUPANCY_CODE	as PMI_OCCUPANCY_CODE
                     , P1.CURRENT_PROPERTY_VALUE
                     , P1.CURRENT_PROPERTY_VALUE_METHOD
                     , P1.CURRENT_COMBINED_LTV
                     , P1.AVM_CALCULATION_METHOD
                     , P1.AVM_DATE
                     , P1.PROPERTY_MOST_RECENT_LOAN
                     , P1.ADDRESS_ID
                     , P1.ORIGINAL_APPRAISED_VALUE
                     , A1.ADDRESS_LINE_1   as PROPERTY_ADDRESS1
                     , A1.ADDRESS_LINE_2   as PROPERTY_ADDRESS2
                     , A1.CITY             as PROPERTY_CITY
                     , A1.STATE            as PROPERTY_STATE
                     , A1.ZIP              as PROPERTY_ZIP
                     , A1.ZIP4			   as PROPERTY_ZIP4
                     , A1.GIS_STATE_COUNTY   as PROPERTY_GIS_STATE_COUNTY
                     , A1.ADDRESS_ID	     as PROPERTY_ADDRESS_ID
					 
               FROM CSRG_PROD.ECR_LOAN L1,
               			CSRG_PROD.ECR_ADDRESS A3,
               			CSRG_PROD.ECR_CUSTOMER C1,
               			CSRG_PROD.ECR_CUSTOMER C2,
               			CSRG_PROD.ECR_ADDRESS A2,
               			CSRG_PROD.ECR_PROPERTY P1,
               			CSRG_PROD.ECR_ADDRESS A1
               WHERE    L1.PRIMARY_CUSTOMER_ID=C1.CUSTOMER_ID
               			and L1.SECONDARY_CUSTOMER_ID=C2.CUSTOMER_ID(+)
               			and L1.LOAN_ADDRESS_ID=A3.ADDRESS_ID
               			and C1.CURRENT_ADDRESS_ID=A2.ADDRESS_ID
                        and L1.PROPERTY_ID=P1.PROPERTY_ID
               			and P1.ADDRESS_ID=A1.ADDRESS_ID
               			and L1.PAYOFF_DATE is NULL
               			and L1.LOAN_STATUS_CODE IN (1, 9)

               ORDER BY L1.ACCOUNT_NUMBER

      		    );

				CREATE table BATCH_PRICING  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(SELECT BPO.* FROM CSRG_PROD.BATCH_PRICING_OUTPUT BPO 
				  WHERE TRANSACTION = 'RATE TERM REFINANCE'
				  AND NEW_PRODUCT LIKE ('%HASP%')
				);

			CREATE table HARP_ELIGIBLE  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(SELECT DISTINCT H.* FROM CSRG_PROD.HARP_ELIGIBLE_NEW H 
				);

			CREATE table APPS  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(SELECT * FROM
(
					SELECT
					PRIOR_ACCOUNT_NO,
					CASE WHEN APP_STATUS_GRP = 'Pipeline' THEN 'PIPELINE'
					WHEN APP_STATUS_GRP = 'Cancelled' AND APP_CANCEL_REASON = 'Declined' AND APP_STATUS_DATE >= SYSDATE - 365 AND APP_SETUP_DATE IS NOT NULL THEN 'DECLINED'
					WHEN APP_STATUS_GRP = 'Cancelled' AND APP_CANCEL_REASON = 'Withdrawn' AND APP_STATUS_DATE >= SYSDATE - 60 AND APP_SETUP_DATE IS NOT NULL THEN 'WITHDRAWN'
					WHEN APP_CREATE_DATE >= SYSDATE - 60 THEN 'ACTIVE PREAPP'
					ELSE '' END AS APP_STATUS,

					APP_STATUS_GRP,

					RANK() OVER (PARTITION BY PRIOR_ACCOUNT_NO order by APP_NO desc) AS RANK
					FROM CSRG_PROD.ECLIPSE_APPS
					WHERE APP_STATUS_GRP <> 'Funded'
					AND APP_CREATE_DATE >= SYSDATE - 365
					)
					WHERE RANK = 1 AND APP_STATUS IS NOT NULL
				);
			
   		DISCONNECT FROM CONN1;
   		
QUIT;

PROC SQL;      
		CONNECT TO ORACLE AS CONN1 (USER=CSRG_PROD ORAPW='MRDM$101' PATH="RENPU") ;
			
			CREATE table SOLICITATION  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(
					SELECT DISTINCT ACCOUNT_NUMBER
					FROM
					(
					SELECT ACCOUNT_NUMBER FROM
					CSRG_PROD.SOLICITATION_HISTORY
					WHERE DISPOSITION_KEY = 8000
					AND CAMPAIGN_KEY IN (22072)

					UNION ALL

					SELECT ACCOUNT_NUMBER FROM RETAIL_LEADS
					WHERE LNOFF_CD IS NOT NULL
					AND ASSIGNABLE_LEAD = 'Y'
					) 
				);
			CREATE table STD_EXCL  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(select * from CSRG_PROD.LOANS_WITH_STD_EXCLUSIONS where CNT_RESTRICT > 0);
   		DISCONNECT FROM CONN1;
   		
QUIT;

PROC SQL;
CREATE TABLE W_DATA AS SELECT
E.ACCOUNT_NUMBER,
E.ASSOCIATION_CODE,
E.GM_OWNED,
E.LIEN_LEVEL_CODE,
/*E.ACTIVE_DUTY_FLAG, from arm snapshot*/
E.STATE,
E.BANKRUPTCY_CODE,
E.ANY_FORECLOSURE_FLAG,
/*E.MAIL_PREF_FLAG, from emap*/
E.DNS_MAIL_FLAG,
E.PROPERTY_STATE,
E.PRODUCT_ID,
E.LOAN_ORIG_DT,
E.FLG_AGE,
E.BAL_PRIN,
E.LOAN_TERM,
/*E.LITIGATION_FLAG, from arm snapshot*/
E.PRIM_NAME_LAST,
E.PRIM_NAME_FIRST,
E.SCND_NAME_LAST,
E.SCND_NAME_FIRST,
E.ADDRESS_1,
E.ADDRESS_2,
E.ZIP,
APP.APP_STATUS,
HRP.FLG_HI,
HRP.FLG_OR,
HRP.FLG_USAA,
HRP.FLG_ALTA,
HRP.FLG_EA,
HRP.FLG_PROP_DAMAGE,
HRP.FLG_GSE_VALUE,
HRP.FLG_KS,
HRP.FLG_WV,
HRP.FLG_NV,
HRP.FLG_OH,
HRP.FLG_SECOND_LIEN_TPS,
HRP.FLG_24F,
HRP.FLG_DELIVERY_DATE,
HRP.FLG_RECOURSE,
HRP.FLG_REPURCHASE,
HRP.FLG_DQ,
HRP.FLG_PAYHISTORY,
HRP.FLG_MI_RECISSION,
HRP.FLG_COOP,
HRP.FLG_MH,
HRP.FLG_MOD,
HRP.FLG_MI_EXCL,
STD.CNT_RESTRICT,
BPO.NEW_PI_SAVINGS_MO,
BPO.MOST_RECENT_PROPERTY_VALUE,
BPO.ADJ_REMAINING_TERM,
BPO.NEW_RATE,
BPO.NEW_FEES_DOL,
BPO.NEW_APR,
BPO.NEW_POINTS_PCT,
BPO.NEW_PRODUCT,
BPO.RATE_DT,
BPO.NEW_TERM,
(BPO.NEW_PI_SAVINGS_MO * 12) AS YEARLY_PAYMENT_SAVINGS,
BPO.LOL_SAVINGS,

CASE WHEN SOL.ACCOUNT_NUMBER = '' THEN 'N' ELSE 'Y' END AS FLG_SOL
FROM ECR_DATAPULL AS E 
LEFT JOIN BATCH_PRICING AS BPO ON (E.ACCOUNT_NUMBER = BPO.ACCOUNT_NUMBER)
LEFT JOIN HARP_ELIGIBLE AS HRP ON (E.ACCOUNT_NUMBER = HRP.ACCOUNT_NUMBER)
LEFT JOIN STD_EXCL AS STD ON (E.ACCOUNT_NUMBER = STD.ACCOUNT_NUMBER)
LEFT JOIN APPS AS APP ON (E.ACCOUNT_NUMBER = APP.PRIOR_ACCOUNT_NO)
LEFT JOIN SOLICITATION AS SOL ON (E.ACCOUNT_NUMBER = SOL.ACCOUNT_NUMBER);
QUIT;

PROC SQL;
CREATE TABLE W_DATA2 AS SELECT ACCOUNT_NUMBER,
CASE WHEN (GM_OWNED = 'N' AND ASSOCIATION_CODE NE '013') THEN '01 - Not GMAC Owned'

WHEN LIEN_LEVEL_CODE NE '01' THEN '02 - Not first Lien'

WHEN STATE NOT IN ('AK','AL','AR','AZ','CA','CO','CT','DC','DE','FL','GA'                              
                   ,'HI','IA','ID','IL','IN','KY','LA','MA','MD','ME','MI','MN'                              
                   ,'MO','MS','MT','NC','ND','NE','NH','NJ','NM','NV','NY','OH'                             
                   ,'OK','OR','PA','RI','SC','SD','TN','TX','UT','VA','VT','WA'                             
                   ,'WI','WV','WY') 
	THEN '03 - Invalid State'

WHEN (RANK(UPCASE(SUBSTR(PRIM_NAME_LAST,1,1)))     lt 65
	or RANK(UPCASE(SUBSTR(PRIM_NAME_LAST,1,1)))  gt 90
	or index(upcase(PRIM_NAME_LAST),'TRUST')     ge 1
	or index(upcase(PRIM_NAME_FIRST),'TRUST')    ge 1
	or index(upcase(SCND_NAME_LAST),'TRUST')     ge 1
	or index(upcase(SCND_NAME_FIRST),'TRUST')    ge 1
	or index(upcase(PRIM_NAME_LAST),'ESTATE')    ge 1
	or index(upcase(PRIM_NAME_FIRST),'ESTATE')   ge 1
	or index(upcase(SCND_NAME_LAST),'ESTATE')    ge 1
	or index(upcase(SCND_NAME_FIRST),'ESTATE')   ge 1
	or index(upcase(ADDRESS_1),'TRUST')          ge 1
	or index(upcase(ADDRESS_2),'TRUST')          ge 1
	or ZIP = '00000'
	or LENGTH(ZIP) LT 5
	or INDEXC(UPCASE(ZIP),'ABCDEFGHIJKLMNOPQRSTUVWXYZ') ge 1
	)
	THEN '04 - Invalid Address'

WHEN APP_STATUS = 'PIPELINE' THEN '05 - Active Pipeline'
WHEN APP_STATUS = 'DECLINED' THEN '06 - Denied App in Last 12 months'
WHEN APP_STATUS = 'WITHDRAWN' THEN '07 - Withdrawn App in Last 6 months'
WHEN APP_STATUS = 'ACTIVE PREAPP' THEN '08 - Active Pre-App'

WHEN FLG_DELIVERY_DATE = 'Y' THEN '09 - GSE Date Exclusion'

WHEN FLG_RECOURSE = 'Y' THEN '10 - Recourse Loan'

WHEN FLG_REPURCHASE = 'Y' THEN '11 - Repurchase Loan'

WHEN FLG_DQ = 'Y' THEN '12 - Active Bankruptcy/ Foreclosure'

WHEN FLG_PAYHISTORY = 'Y' THEN '13 - Delinquency (12 month)'

WHEN FLG_MI_RECISSION = 'Y' THEN '14 - MI Rescinded'

WHEN FLG_COOP = 'Y' OR FLG_MH = 'Y' OR FLG_MOD = 'Y' THEN '15 - Property Type Exclusions'

WHEN FLG_GSE_VALUE = 'Y' THEN '16 - GSE Value Not Available'

WHEN FLG_ALTA = 'Y' OR FLG_EA = 'Y' THEN '17 - Alt A and Expanded Approval'

WHEN FLG_PROP_DAMAGE = 'Y' OR FLG_SECOND_LIEN_TPS = 'Y' OR FLG_24F = 'Y' THEN '18 - Prop Damage, TPS 2nd liens & Multi Units'

WHEN PROPERTY_STATE IN ('KS', 'WV'/*, 'NV', 'OH'*/) THEN '19 - State Exclusions (KS, WV, NV, OH)'

WHEN FLG_MI_EXCL = 'Y' THEN '20 - MI Exclusions'

WHEN FLG_MOD = 'Y' THEN '21 - Loan Modification'

WHEN ASSOCIATION_CODE = '013' THEN '22 - USAA Loan'

WHEN CNT_RESTRICT NE . THEN '23 - Standard Exclusions'

WHEN DNS_MAIL_FLAG IN ('Y','E') THEN '24 - Dot Not Mail'

WHEN PROPERTY_STATE IN ('HI'/*, 'OR'*/, 'AR') THEN '25 - State Exclusions (HI, AR)'

WHEN PROPERTY_STATE IN ('TX') and PRODUCT_ID in ('472','471','537','538','736','738','W16','W17',
'X35','X45','X65','X82','Y06','Y07','Y08','Y09','HE024','HE025','HE026','HE033','HE034','HE039','HE041',
'HE070','HE071','HE072','HE073','HE074','HE075','HE076','HE077','HE101','HE102','HE103','HE104','HE105',
'HE106') THEN '26 - TX Home Equity Exclusion'

WHEN PROPERTY_STATE IN ('TX') AND MOST_RECENT_PROPERTY_VALUE > 0 AND BAL_PRIN/MOST_RECENT_PROPERTY_VALUE > 0.80 
THEN '27 - TX Over 80 LTV Exclusion'

WHEN FLG_AGE = 'Y' THEN '28 - Loan Age' 

WHEN BAL_PRIN < 50000 THEN '29 - Unpaid Balance < $50K'

WHEN ADJ_REMAINING_TERM = . OR ADJ_REMAINING_TERM < 96 THEN '30 - Adjusted Remaining Term < 8 yrs'

WHEN BAL_PRIN/MOST_RECENT_PROPERTY_VALUE <= 0.80 THEN '31 - LTV < 80%'

WHEN NEW_PI_SAVINGS_MO = . OR NEW_PI_SAVINGS_MO < 100 THEN '32 - New PI Savings < $100'

WHEN NEW_APR - NEW_RATE > .6 THEN '33 - APR Higher than Rate'

WHEN FLG_SOL = 'Y' THEN '33 - In Prior Campaigns'

ELSE 'Selected' END AS EXCL_CRITERIA

FROM W_DATA;
QUIT;

PROC SQL;
CREATE TABLE W_DATA3 AS SELECT 
EXCL_GRP, EXCL_CRITERIA, COUNT(*) AS NO_OF_LOANS
FROM
(
SELECT
CASE WHEN INPUT(SUBSTR(EXCL_CRITERIA, 1, 2), 2.) < 9 THEN 'General Campaign Exclusions'
WHEN INPUT(SUBSTR(EXCL_CRITERIA, 1, 2), 2.) < 16 THEN 'HARP Program Exclusions'
WHEN INPUT(SUBSTR(EXCL_CRITERIA, 1, 2), 2.) < 22 THEN 'HARP Operational Exclusions'
ELSE 'Marketing Exclusions' END AS EXCL_GRP,
A.*
FROM W_DATA2 AS A
) 
GROUP BY EXCL_GRP, EXCL_CRITERIA;
QUIT;

libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

proc sql noprint;
select SOLICITATION_KEY FORMAT = 20.
into : SOL_K
from (SELECT MAX(SOLICITATION_KEY) AS SOLICITATION_KEY FROM CSRG.SOLICITATION_HISTORY S where solicitation_key <  1000000000000);
QUIT;

LIBNAME CSRG CLEAR;

%PUT &SOL_K;

PROC SQL;
CREATE TABLE SOL_H AS SELECT
&SOL_K + MONOTONIC() AS SOLICITATION_KEY FORMAT = 20.,
PRIMARY_CUSTOMER_ID AS CUSTOMER_ID,
TRIM(R.ACCOUNT_NUMBER) AS ACCOUNT_NUMBER LENGTH = 10,
'' AS PROGRAM_INDICATOR LENGTH = 3,
'SOL' AS METHOD_CODE LENGTH = 6,
'' AS FILE_NAME LENGTH = 30,
TODAY() AS FILE_OUT_DATE FORMAT = MMDDYY10.,
22079 AS CAMPAIGN_KEY,
70496 AS CELL_KEY,
. AS CREATIVE_KEY,
. AS OFFER_KEY,
'N' AS CONTROL_GROUP_INDICATOR LENGTH = 1,
9999 AS DISPOSITION_KEY,
TODAY() AS DISPOSITION_DATE  FORMAT = MMDDYY10.,
'' AS VEND_FILE_ID LENGTH = 20,
'' AS VEND_CAMPAIGN_KEY LENGTH = 20,
'' AS VEND_CELL_KEY LENGTH = 20,
'' AS VEND_CREATIVE_KEY LENGTH = 20,
'' AS VEND_OFFER_KEY LENGTH = 20,
'' AS VEND_INPUT1 LENGTH = 20,
. AS PROCESSED_PROCESS_SEQ,
. AS LOAD_ID,
TODAY() AS ADDED_DATE  FORMAT = MMDDYY10.,
'atrip' AS ADDED_BY LENGTH = 20,
. AS UPDATED_DATE FORMAT = DATETIME20.,
'' AS UPDATED_BY LENGTH = 20,
PRIMARY_SSN AS CUST_PRIM_SSN LENGTH = 9,
SECONDARY_SSN AS CUST_SCND_SSN LENGTH = 9,
. AS VENDOR_KEY,
'HARP RT 201302' AS CAMPAIGN_ID LENGTH = 15,
'' AS MARKETING_CHANNEL LENGTH = 14,
'' AS ORIGINATION_CHANNEL LENGTH = 14, 
. AS SW_MAILING_ID,
. AS SW_CALCULATION_ID,
BAL_PRIN,
. AS LINE_COMMIT_AMT,
. AS TM_DISPOSITION_KEY,
. AS TM_DISPOSITION_DATE FORMAT = DATETIME20.,
'' AS MISC_TEXT1 LENGTH = 20,
'' AS MISC_TEXT2 LENGTH = 20,
'' AS  MISC_TEXT3 LENGTH = 50,
SECONDARY_CUSTOMER_ID,
'' AS MKT_CONTACT_BRANCH_ID LENGTH = 12,
. AS MKT_CONTACT_EMP_ID,
'' AS MKT_CONTACT_NAME LENGTH = 50,
'' AS MKT_CONTACT_WHICH LENGTH = 25,
'' AS MKT_CONTACT_PHONE LENGTH = 25

FROM LEAD_ALLOCATION AS R, ECR_DATAPULL AS A
WHERE A.ACCOUNT_NUMBER = R.ACCOUNT_NUMBER;
QUIT;
 
libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

PROC APPEND BASE = CSRG.SOLICITATION_HISTORY DATA = SOL_H; RUN;

LIBNAME CSRG CLEAR;


libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

proc sql noprint;
select SOLICITATION_KEY FORMAT = 20.
into : SOL_K
from (SELECT MAX(SOLICITATION_KEY) AS SOLICITATION_KEY FROM CSRG.SOLICITATION_HISTORY S where solicitation_key <  1000000000000);
QUIT;

LIBNAME CSRG CLEAR;


PROC SQL;
CREATE TABLE DMU80 AS SELECT DISTINCT A.ACCOUNT_NUMBER FROM W_DATA2 AS A LEFT JOIN LEAD_ALLOCATION AS B
ON A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER
WHERE B.ACCOUNT_NUMBER = '' AND A.EXCL_CRITERIA = 'Selected';
QUIT;

PROC SURVEYSELECT DATA=DMU80
	OUT=DMU801
	METHOD=SRS
	N=10000
	;
RUN;

PROC SQL;
CREATE TABLE SOL_H1 AS SELECT
&SOL_K + MONOTONIC() AS SOLICITATION_KEY FORMAT = 20.,
PRIMARY_CUSTOMER_ID AS CUSTOMER_ID,
TRIM(R.ACCOUNT_NUMBER) AS ACCOUNT_NUMBER LENGTH = 10,
'' AS PROGRAM_INDICATOR LENGTH = 3,
'SOL' AS METHOD_CODE LENGTH = 6,
'' AS FILE_NAME LENGTH = 30,
TODAY() AS FILE_OUT_DATE FORMAT = MMDDYY10.,
22078 AS CAMPAIGN_KEY,
70495 AS CELL_KEY,
. AS CREATIVE_KEY,
. AS OFFER_KEY,
'N' AS CONTROL_GROUP_INDICATOR LENGTH = 1,
9999 AS DISPOSITION_KEY,
TODAY() AS DISPOSITION_DATE  FORMAT = MMDDYY10.,
'' AS VEND_FILE_ID LENGTH = 20,
'' AS VEND_CAMPAIGN_KEY LENGTH = 20,
'' AS VEND_CELL_KEY LENGTH = 20,
'' AS VEND_CREATIVE_KEY LENGTH = 20,
'' AS VEND_OFFER_KEY LENGTH = 20,
'' AS VEND_INPUT1 LENGTH = 20,
. AS PROCESSED_PROCESS_SEQ,
. AS LOAD_ID,
TODAY() AS ADDED_DATE  FORMAT = MMDDYY10.,
'atrip' AS ADDED_BY LENGTH = 20,
. AS UPDATED_DATE FORMAT = DATETIME20.,
'' AS UPDATED_BY LENGTH = 20,
PRIMARY_SSN AS CUST_PRIM_SSN LENGTH = 9,
SECONDARY_SSN AS CUST_SCND_SSN LENGTH = 9,
. AS VENDOR_KEY,
'HARP DM 201302' AS CAMPAIGN_ID LENGTH = 15,
'' AS MARKETING_CHANNEL LENGTH = 14,
'' AS ORIGINATION_CHANNEL LENGTH = 14, 
. AS SW_MAILING_ID,
. AS SW_CALCULATION_ID,
BAL_PRIN,
. AS LINE_COMMIT_AMT,
. AS TM_DISPOSITION_KEY,
. AS TM_DISPOSITION_DATE FORMAT = DATETIME20.,
'' AS MISC_TEXT1 LENGTH = 20,
'' AS MISC_TEXT2 LENGTH = 20,
'' AS  MISC_TEXT3 LENGTH = 50,
SECONDARY_CUSTOMER_ID,
'' AS MKT_CONTACT_BRANCH_ID LENGTH = 12,
. AS MKT_CONTACT_EMP_ID,
'' AS MKT_CONTACT_NAME LENGTH = 50,
'' AS MKT_CONTACT_WHICH LENGTH = 25,
'' AS MKT_CONTACT_PHONE LENGTH = 25

FROM DMU801 AS R, ECR_DATAPULL AS A
WHERE A.ACCOUNT_NUMBER = R.ACCOUNT_NUMBER;
QUIT;

libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

PROC APPEND BASE = CSRG.SOLICITATION_HISTORY DATA = SOL_H1; RUN;

LIBNAME CSRG CLEAR;



libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

proc sql noprint;
select SOLICITATION_KEY FORMAT = 20.
into : SOL_K
from (SELECT MAX(SOLICITATION_KEY) AS SOLICITATION_KEY FROM CSRG.SOLICITATION_HISTORY S where solicitation_key <  1000000000000);
QUIT;

LIBNAME CSRG CLEAR;



PROC SQL;
CREATE TABLE DMUO0 AS SELECT DISTINCT A.ACCOUNT_NUMBER FROM W_DATA2 AS A 
WHERE A.EXCL_CRITERIA = 'Selected';
QUIT;

PROC SURVEYSELECT DATA=DMUO0
	OUT=DMUO01
	METHOD=SRS
	N=13000
	;
RUN;

PROC SQL;
CREATE TABLE SOL_H2 AS SELECT
&SOL_K + MONOTONIC() AS SOLICITATION_KEY FORMAT = 20.,
PRIMARY_CUSTOMER_ID AS CUSTOMER_ID,
TRIM(R.ACCOUNT_NUMBER) AS ACCOUNT_NUMBER LENGTH = 10,
'' AS PROGRAM_INDICATOR LENGTH = 3,
'SOL' AS METHOD_CODE LENGTH = 6,
'' AS FILE_NAME LENGTH = 30,
TODAY() AS FILE_OUT_DATE FORMAT = MMDDYY10.,
22078 AS CAMPAIGN_KEY,
70494 AS CELL_KEY,
. AS CREATIVE_KEY,
. AS OFFER_KEY,
'N' AS CONTROL_GROUP_INDICATOR LENGTH = 1,
9999 AS DISPOSITION_KEY,
TODAY() AS DISPOSITION_DATE  FORMAT = MMDDYY10.,
'' AS VEND_FILE_ID LENGTH = 20,
'' AS VEND_CAMPAIGN_KEY LENGTH = 20,
'' AS VEND_CELL_KEY LENGTH = 20,
'' AS VEND_CREATIVE_KEY LENGTH = 20,
'' AS VEND_OFFER_KEY LENGTH = 20,
'' AS VEND_INPUT1 LENGTH = 20,
. AS PROCESSED_PROCESS_SEQ,
. AS LOAD_ID,
TODAY() AS ADDED_DATE  FORMAT = MMDDYY10.,
'atrip' AS ADDED_BY LENGTH = 20,
. AS UPDATED_DATE FORMAT = DATETIME20.,
'' AS UPDATED_BY LENGTH = 20,
PRIMARY_SSN AS CUST_PRIM_SSN LENGTH = 9,
SECONDARY_SSN AS CUST_SCND_SSN LENGTH = 9,
. AS VENDOR_KEY,
'HARP DM 201302' AS CAMPAIGN_ID LENGTH = 15,
'' AS MARKETING_CHANNEL LENGTH = 14,
'' AS ORIGINATION_CHANNEL LENGTH = 14, 
. AS SW_MAILING_ID,
. AS SW_CALCULATION_ID,
BAL_PRIN,
. AS LINE_COMMIT_AMT,
. AS TM_DISPOSITION_KEY,
. AS TM_DISPOSITION_DATE FORMAT = DATETIME20.,
'' AS MISC_TEXT1 LENGTH = 20,
'' AS MISC_TEXT2 LENGTH = 20,
'' AS  MISC_TEXT3 LENGTH = 50,
SECONDARY_CUSTOMER_ID,
'' AS MKT_CONTACT_BRANCH_ID LENGTH = 12,
. AS MKT_CONTACT_EMP_ID,
'' AS MKT_CONTACT_NAME LENGTH = 50,
'' AS MKT_CONTACT_WHICH LENGTH = 25,
'' AS MKT_CONTACT_PHONE LENGTH = 25

FROM DMUO01 AS R, ECR_DATAPULL AS A
WHERE A.ACCOUNT_NUMBER = R.ACCOUNT_NUMBER;
QUIT;

libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

PROC APPEND BASE = CSRG.SOLICITATION_HISTORY DATA = SOL_H2; RUN;

LIBNAME CSRG CLEAR;


PROC SQL;      
		CONNECT TO ORACLE AS CONN1 (USER=CSRG_PROD ORAPW='MRDM$101' PATH="RENPU") ;
			
			CREATE table MAIL_FILE  AS
      		SELECT  *
      		FROM CONNECTION TO CONN1
          		(
				SELECT
				C1.LAST_NAME AS LAST_NAME_PRIM,
				C1.FIRST_NAME AS FIRST_NAME_PRIM,
				C2.LAST_NAME AS LAST_NAME_SECD,
				C2.FIRST_NAME AS FIRST_NAME_SECD,
				A2.ADDRESS_LINE_1 AS ADDRESS1,
				A2.ADDRESS_LINE_2 AS ADDRESS2,
				A2.CITY AS CITY,
				A2.STATE AS STATE,
				A2.ZIP AS ZIP,
				C1.EMAIL_ADDRESS AS EMAIL_ADDRESS,
				ROUND(E.INTEREST_RATE * 100, 3) AS CURRENT_RATE,
				E.PRINCIPAL_AND_INTEREST AS CURRENT_PI,
				E.RATE_TYPE AS MRG_RATE_TYPE,
				E.UNPAID_BALANCE AS CURRENT_BALANCE,
				NULL AS PAYMENT_RATE_ADJ_DATE,
				C1.RELATIONSHIP_START_DATE,
				S.ACCOUNT_NUMBER AS ACCT_NUM,
				S.CELL_KEY AS CAMPAIGN_CELL_ID,
				S.CAMPAIGN_KEY AS CAMPAIGN_ID,
				S.CAMPAIGN_ID AS CAMPAIGN_NAME,
				S.SOLICITATION_KEY AS CONTACT_ID,
				BPO.NEW_PRODUCT,
				BPO.NEW_RATE,
				BPO.NEW_APR,
				BPO.NEW_POINTS_PCT AS NEW_POINTS,
				BPO.NEW_FEES_DOL AS NEW_FEES,
				BPO.NEW_PI,
				BPO.NEW_PI_SAVINGS_MO AS NEW_PI_SAVINGS,
				BPO.NEW_TERM,
				BPO.NEW_PI_SAVINGS_MO * 12 AS YEARLY_PAYMENT_SAVINGS,
				NULL AS New_Cash,
				NULL AS New_Cash_SAMEPI,
				BPO.MOST_RECENT_PROPERTY_VALUE AS PROPERTY_VALUE,
				TO_DATE('01/01/2013','MM/DD/YYYY') AS PROPERTY_VALUE_DATE,
				BPO.RATE_DT AS RATE_PULL_DATE,
				BPO.LOL_SAVINGS,
				NULL AS Flex_1,
				E.LOAN_TERM AS Flex_2,
				BPO.ADJ_REMAINING_TERM AS Flex_3,
				BPO.TERM_REDUCTION AS Flex_4,
				NULL AS Flex_5,
				NULL AS Flex_6,
				E.ORIGINATION_DATE AS Flex_7,
				NULL AS Flex_8,
				NULL AS Flex_9,
				NULL AS Flex_10,
				NULL AS Flex_11,
				NULL AS Flex_12,
				A1.ADDRESS_LINE_1 AS Flex_13,
				A1.ADDRESS_LINE_2 AS Flex_14,
				A1.CITY AS Flex_15,
				A1.STATE AS Flex_16,
				A1.ZIP AS Flex_17,
				R.LNOFF_NAME AS Flex_18,
				R.FNAME AS Flex_19,
				R.LNAME AS Flex_20,
				LNOFF_PHONE AS Flex_21,
				LNOFF_EMAIL AS Flex_22,
				LNOFF_NMLS AS Flex_23,
				LNOFF_LIC_STATES AS Flex_24

				FROM (SELECT * FROM CSRG_PROD.SOLICITATION_HISTORY WHERE CAMPAIGN_KEY IN (22078, 22079)) S,
				ECR_LOAN E,
				ECR_ADDRESS A1,
				ECR_ADDRESS A2,
				ECR_PROPERTY P,
				ECR_CUSTOMER C1,
				ECR_CUSTOMER C2,
				(
				SELECT
				RL.ACCOUNT_NUMBER,
				RL.LNOFF_CD,
				RP.LNOFF_NAME,
				RP.LNOFF_EMAIL,
				RP.LNOFF_PHONE,
				RP.LNOFF_NMLS,
				RP.LNOFF_LIC_STATES,
				U.FNAME,
				U.LNAME
				FROM RETAIL_LEADS RL, RETAIL_LOS RP, PUB.USERS@DTRPTP U
				WHERE RL.LNOFF_CD = RP.LNOFF_CD
				AND RP.LNOFF_CD = U.USER_CD
				AND RL.LNOFF_CD IS NOT NULL
				AND RL.ASSIGNABLE_LEAD = 'Y'
				AND RL.LIST_ID = 'RETAIL LO HARP FEB 13-A'
				) R,

				(
				SELECT A.*
				FROM CSRG_PROD.BATCH_PRICING_OUTPUT A
				WHERE TRANSACTION = 'RATE TERM REFINANCE' AND NEW_PRODUCT LIKE ('%HASP%')
				) BPO

				WHERE S.ACCOUNT_NUMBER = E.ACCOUNT_NUMBER
				AND E.PROPERTY_ID = P.PROPERTY_ID
				AND E.PRIMARY_CUSTOMER_ID = C1.CUSTOMER_ID
				AND E.SECONDARY_CUSTOMER_ID = C2.CUSTOMER_ID(+)
				AND P.ADDRESS_ID = A1.ADDRESS_ID
				AND C1.CURRENT_ADDRESS_ID=A2.ADDRESS_ID
				AND S.ACCOUNT_NUMBER = BPO.ACCOUNT_NUMBER
				AND S.ACCOUNT_NUMBER = R.ACCOUNT_NUMBER(+)

				);
			
   		DISCONNECT FROM CONN1;
   		
QUIT;

libname csrg  oracle user=CSRG_PROD password='mrdm$101' path=RENPU schema=CSRG_PROD;

PROC SQL;
DROP TABLE CSRG.MAIL_FILE;
CREATE TABLE CSRG.MAIL_FILE AS SELECT * FROM MAIL_FILE;
QUIT;

LIBNAME CSRG CLEAR;
